url: http://www.tamartrades.co.uk
baseurl: /

# Site settings
title: Tamar Trades
email: tamartrades@gmail.com
description: "Full service building, renovations, interiors and landscaping in the Tamar Valley, UK."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 17688E
  secondary: A6CF42
  secondary-dark: 333


people:
- name: Justin Newman
  pic: jn.png
  position: Director

- name: Donna Prescott
  pic: donna.jpg
  position: Director
  social:







# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/bigfudge
#   # - title: facebook
#   #   url:

# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
